<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;
use CodeIgniter\I18n\Time;

class AkunPengeluaranSeeder extends Seeder
{
    public function run()
    {
        $now = Time::now('Asia/Jakarta', 'en_US');
        $data = array(
            array('kode_akun' => '5000-1000', 'nama_akun' => 'Biaya Administrasi dan Umum', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1010', 'nama_akun' => 'Gaji Dosen dan Karyawan Tetap', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1011', 'nama_akun' => 'Honor Karyawan Tidak Tetap', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1012', 'nama_akun' => 'Honorarium Dosen Tidak Tetap', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1013', 'nama_akun' => 'Honor/Tunjangan Non Rutin', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1014', 'nama_akun' => 'Insentif Rapat', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1015', 'nama_akun' => 'Insentif lembur', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1016', 'nama_akun' => 'Konsumsi rapat/lembur', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1017', 'nama_akun' => 'Biaya Perjalanan Dinas', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1018', 'nama_akun' => 'Biaya Kegiatan Praktikum', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1030', 'nama_akun' => 'Alat Tulis Kantor', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1032', 'nama_akun' => 'Administrasi Kantor & Fto copy', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1033', 'nama_akun' => 'Administrasi Bank', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1034', 'nama_akun' => 'Listrik/Air/Komunikasi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1035', 'nama_akun' => 'Keperluan dapur/konsumsi rutin', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1050', 'nama_akun' => 'Angsuran Pinjaman k Pihak III', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1080', 'nama_akun' => 'Biaya Lain-lain', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1090', 'nama_akun' => 'Perawatan Lab. Komputer', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1092', 'nama_akun' => 'Perawatan Gedung dan Sapras', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-2000', 'nama_akun' => 'Biaya Ujian', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-2010', 'nama_akun' => 'Biaya UTS', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-2020', 'nama_akun' => 'Biaya UAS', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-2030', 'nama_akun' => 'Biaya Ujian Susulan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-2040', 'nama_akun' => 'Biaya & Insentif TA', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-2050', 'nama_akun' => 'PA & Tugas Proyek', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-2060', 'nama_akun' => 'Biaya/Insentif PKL & KKN', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-3000', 'nama_akun' => 'Biaya Kegiatan Mahasiswa', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-3100', 'nama_akun' => 'Biaya Kegiatan Penelitian', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-3200', 'nama_akun' => 'Biaya Kegiatan DAT', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-4000', 'nama_akun' => 'Biaya Maba', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-4010', 'nama_akun' => 'Biaya Promosi Maba', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-4020', 'nama_akun' => 'Komisi Biaya Pendaftaran', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-4030', 'nama_akun' => 'Biaya Penerimaan Maba', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-4040', 'nama_akun' => 'Discount Maba', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-5000', 'nama_akun' => 'Biaya Pengembangan Institusi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-5010', 'nama_akun' => 'Biaya lokakarya kurikulum ', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-5020', 'nama_akun' => 'Bantuan Kuliah S2', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-5030', 'nama_akun' => 'Biaya Akreditasi S1', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-5050', 'nama_akun' => 'Biaya Promosi Stikom', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-5090', 'nama_akun' => 'Pembelian komputer & sapras ', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-5100', 'nama_akun' => 'Pembelian Peralatan Kantor', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-6000', 'nama_akun' => 'Yayasan & Asuransi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-6010', 'nama_akun' => 'Asuransi Karyawan & Dosen', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-6020', 'nama_akun' => 'Arisan Keluarga Yayasan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-6030', 'nama_akun' => 'Setoran k Yayasan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-6050', 'nama_akun' => 'Setoran k BNI', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '7000-1001', 'nama_akun' => 'Biaya Pembangunan Musholla', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-3300', 'nama_akun' => 'Kegiatan Pengabdian Masyarakat', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-5040', 'nama_akun' => 'PHP-PTS/HIBAH', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-3400', 'nama_akun' => 'Kewirausahaan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1019', 'nama_akun' => 'Insentif Kepanitian', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-5011', 'nama_akun' => 'biaya lisensi software', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1020', 'nama_akun' => 'Yudisium & Wisuda', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1021', 'nama_akun' => 'Proses Ijazah & Transkrip', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-5021', 'nama_akun' => 'Bantuan dari lembaga', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1082', 'nama_akun' => 'Pot. Koperasi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '5000-1023', 'nama_akun' => 'Pelatihan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-110', 'nama_akun' => 'Akreditasi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-130', 'nama_akun' => 'Hutang & Iuran PPLP', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-184', 'nama_akun' => 'Insentif Rapat Pagi & Rapim', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-187', 'nama_akun' => 'Hutang Karyawan/Hutang Kegiatan Peneliti', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-188', 'nama_akun' => 'PBB', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-189', 'nama_akun' => 'Reuni', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-191', 'nama_akun' => 'VCD & Rekaman', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-192', 'nama_akun' => 'Insentif DPA', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-193', 'nama_akun' => 'Sarasehan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-195', 'nama_akun' => 'Kelas Khusus', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-196', 'nama_akun' => 'Kuliah Umum', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-197', 'nama_akun' => 'Ijazah & Prosesi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-198', 'nama_akun' => 'Biaya Workshop & Penelitian', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-199', 'nama_akun' => 'Diskon Maba', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-200', 'nama_akun' => 'Peningkatan SDM (Pelatihan Pekerti & AA)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-201', 'nama_akun' => 'Peningkatan SDM (Program Layanan Prima)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-202', 'nama_akun' => 'Benchmarking (ketua, puket, kabag)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-204', 'nama_akun' => 'Renovasi Pagar Belakang', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-02-205', 'nama_akun' => 'Renovasi Pos Satpam', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-205', 'nama_akun' => 'Renovasi Kantin, Gudang', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-206', 'nama_akun' => 'Renovasi Ruang Santai & UKM', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-207', 'nama_akun' => 'Pengadaan Buku Perpustakaan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-208', 'nama_akun' => 'Renovasi Lab (Penggantian Monitor Lab)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-209', 'nama_akun' => 'Renovasi Lantai 1 (granit)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-210', 'nama_akun' => 'Renovasi AC aula', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-211', 'nama_akun' => 'Sound Sistem + Arisan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-212', 'nama_akun' => 'Pembelian Kendaraan Kampus', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-2013', 'nama_akun' => 'Pembangunan Gedung Baru', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-214', 'nama_akun' => 'Prediksi Piutang Mahasiswa', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-215', 'nama_akun' => 'Pembelihan Hewan Qurban', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-216', 'nama_akun' => 'Pembelian Lahan untuk Pengembangan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-100', 'nama_akun' => 'Rapat Kerja Bidang 1', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-110', 'nama_akun' => 'Sosialisasi Kegiatan Akademik', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-120', 'nama_akun' => 'Pembuatan Buku Ajar (5 mata kuliah)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-130', 'nama_akun' => 'Pembuatan Modul Praktikum/B.Praktikum&in', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-131', 'nama_akun' => 'Skripsi/TA', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-132', 'nama_akun' => 'Tugas Proyek', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-133', 'nama_akun' => 'PKL/KKN', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-134', 'nama_akun' => 'Ujian Susulan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-135', 'nama_akun' => 'Biaya Konversi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-140', 'nama_akun' => 'biaya Dosen Pengajar (6 mata kuliah)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-141', 'nama_akun' => 'Biaya konsumsi (18 dosen)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-142', 'nama_akun' => 'Biaya Transport (18 dosen)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-143', 'nama_akun' => 'Biaya Penginapan (18 dosen)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-144', 'nama_akun' => 'Upgrade Internal Dosen', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-150', 'nama_akun' => 'UTS semester ganjil', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-151', 'nama_akun' => 'UAS Semester Ganjil', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-152', 'nama_akun' => 'UTS Semester Genap', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1-153', 'nama_akun' => 'UAS Semester Genap', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2-100', 'nama_akun' => 'Biaya Gaji Pejabat & Karyawan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2-110', 'nama_akun' => 'Honor Dosen Tidak Tetap', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2-120', 'nama_akun' => 'Rapat Kerja Bidang II', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2-130', 'nama_akun' => 'Kepanitian Registrasi semester Ganjil', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2-131', 'nama_akun' => 'Kepanitian Registrasi semester Genap', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2-132', 'nama_akun' => 'Kepanitian Program Hibah Dikti', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2-133', 'nama_akun' => 'Kepanitian Pengadaan&Renov. smstr Genap', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2-134', 'nama_akun' => 'Kepanitian Pengadaan&Renov smstr ganjil', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2-140', 'nama_akun' => 'Tunjangan Sosial', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2-150', 'nama_akun' => 'Pengembangan SDM', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-100', 'nama_akun' => 'Rapat Kerja Bidang III', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-120', 'nama_akun' => 'Penerbitan Jurnal', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-121', 'nama_akun' => 'Penelitian', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-122', 'nama_akun' => 'Seminar Regional Penelitian', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-123', 'nama_akun' => 'Buku Panduan Akademik', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-130', 'nama_akun' => 'Kegiatan Pengabdian masyarakat', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-140', 'nama_akun' => 'Promosi /Stikom Berbagi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-150', 'nama_akun' => 'Pengembangan minat Bakat Mahasiswa', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-151', 'nama_akun' => 'Pemberdayaan Alumni', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-152', 'nama_akun' => 'Bursa kerja', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-153', 'nama_akun' => 'Temu Alumni', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-155', 'nama_akun' => 'Program kreatifitas Mhs/Kegiatan Mhs', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-160', 'nama_akun' => 'Kewirausahaan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-161', 'nama_akun' => 'Asuransi Mahasiswa', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-162', 'nama_akun' => 'Komisi maba', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-163', 'nama_akun' => 'Penerimaan Maba', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-164', 'nama_akun' => 'PLK', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-165', 'nama_akun' => 'Yudisium & Wisuda', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-217', 'nama_akun' => 'Renovasi Ruang Ketua', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-403', 'nama_akun' => 'Peningkatan Kinerja Pimpinan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3-166', 'nama_akun' => 'Penerimaan STIKOM Peduli/Berbagi/Survey', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0-321', 'nama_akun' => 'Kantin (Subsidi Kantin)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0000', 'nama_akun' => 'Saving Dana (Non Pengembangan)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0001', 'nama_akun' => 'Perjalanan Dinas', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0002', 'nama_akun' => 'Akreditasi & Visitasi Institusi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0003', 'nama_akun' => 'Akreditasi & Borang Ti', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0005', 'nama_akun' => 'Hibah (Proposal)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0006', 'nama_akun' => 'Proposal (Dana Pendamping)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0007', 'nama_akun' => 'Hutang Bank', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0008', 'nama_akun' => 'Iuran PPLP-PT PGRI Banyuwangi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0009', 'nama_akun' => 'Iuran PGRI PUSAT', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0011', 'nama_akun' => 'UPT Promosi (Kalender)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0012', 'nama_akun' => 'UPT Promosi (Brosur)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0013', 'nama_akun' => 'UPT Promosi (Spanduk)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0014', 'nama_akun' => 'UPT Promosi (Radio)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0016', 'nama_akun' => 'Presentasi (Kab.BWI)-Survey/Sosialisasi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0017', 'nama_akun' => 'Presentasi (Kab.BWI)-Penitipan Brosur', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0018', 'nama_akun' => 'Presentasi (Kab.BWI)-Fee Sekolah (sosial', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0019', 'nama_akun' => 'Presentasi (Kab.BWI)-Insentif Dosen', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0020', 'nama_akun' => 'Presentasi (Kab.BWI)-Insentif Mahasiswa/', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0021', 'nama_akun' => 'Presentasi (Kab.BWI)-Konsumsi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0022', 'nama_akun' => 'Presentasi (Kab.BWI)-Transport', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0024', 'nama_akun' => 'Presentasi (Bali)-Survey/Sosialisasi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0025', 'nama_akun' => 'Presentasi (Bali)-Penitipan Brosur', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0026', 'nama_akun' => 'Presentasi (Bali)-Fee Sekolah (sosialisa', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0027', 'nama_akun' => 'Presentasi (Bali)-Insentif Dosen', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0028', 'nama_akun' => 'Presentasi (Bali)-Instf. Mahasiswa/Petug', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0029', 'nama_akun' => 'Presentasi (Bali)-Konsumsi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0030', 'nama_akun' => 'Presentasi (Bali)-Transport', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0032', 'nama_akun' => 'Promosi Melalui Masjid', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0033', 'nama_akun' => 'Pameran', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0034', 'nama_akun' => 'Multimedia', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0035', 'nama_akun' => 'Lomba/Pelatihan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0036', 'nama_akun' => 'Pemberian Komisi Sponsor MABA', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0037', 'nama_akun' => 'Pemberian Komisi ke sekolah', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0039', 'nama_akun' => 'Sarana Promosi (LCD Proyektor)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0040', 'nama_akun' => 'UPT STIKOM Development Center (SDC)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0041', 'nama_akun' => 'Kantin (Subsidi Gaji Karyawan)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0042', 'nama_akun' => 'Pengembangan Institusi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0044', 'nama_akun' => 'Besiswa STIKOM Berbagi (S1)-2012', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0045', 'nama_akun' => 'Besiswa STIKOM Berbagi (S1)-2013', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0046', 'nama_akun' => 'Besiswa STIKOM Berbagi (S1)-2014', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0047', 'nama_akun' => 'Besiswa STIKOM Berbagi (S1)-2015', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0049', 'nama_akun' => 'Besiswa STIKOM Berbagi (D3)-2013', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0050', 'nama_akun' => 'Besiswa STIKOM Berbagi (D3)-2014', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0051', 'nama_akun' => 'Besiswa STIKOM Berbagi (D3)-2015', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0053', 'nama_akun' => 'Diskon Karyawan & Anggota PGRI', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0056', 'nama_akun' => 'Pengadaan Komputer Lab', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0057', 'nama_akun' => 'Pengadaan Komputer (Lab.Multimedia)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0058', 'nama_akun' => 'Renovasi Komputer Lab & Server', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0059', 'nama_akun' => 'Renovasi R.Rapat,Lab,R.Kuliah,Teras dll', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0060', 'nama_akun' => 'Kursi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0061', 'nama_akun' => 'Sound Systim', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0062', 'nama_akun' => 'Meja', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0063', 'nama_akun' => 'Dispencer', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0064', 'nama_akun' => 'Lemari Es (Ketua)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0065', 'nama_akun' => 'Renovasi Ruang Ketua', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0066', 'nama_akun' => 'Renovasi Bangunan R.Santai & Mushola', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0067', 'nama_akun' => 'Renovasi Ruang Ketua Lab.', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0068', 'nama_akun' => 'Renovasi Ruang Perpustakaan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0069', 'nama_akun' => 'Renovasi Ruang LPPM', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0073', 'nama_akun' => 'Peningkatan SDM (Pelatihan Pekerti & AA)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0074', 'nama_akun' => 'Peningkatan SDM (Sertifikasi Profesi)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0075', 'nama_akun' => 'Peningkatan SDM (Upgrade Dosen)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0076', 'nama_akun' => 'Peningkatan SDM (Program Layanan Prima)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0077', 'nama_akun' => 'Peningkatan Kinerja Pimpinan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0078', 'nama_akun' => 'Benchmarking', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0079', 'nama_akun' => 'Peningkatan SDM (studi lanjut & kepangka', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0082', 'nama_akun' => 'Prediksi Piutang Mahasiswa', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0083', 'nama_akun' => 'Penyembelihan Qurban', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0084', 'nama_akun' => 'Rapim', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1000', 'nama_akun' => 'Rapat Kerja Bidang I', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1001', 'nama_akun' => 'Sosialisasi Kegiatan Akademik(Buku Pandu', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1002', 'nama_akun' => 'Pembuatan Buku Ajar (10MK)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1003', 'nama_akun' => 'Pembuatan Modul Praktikum &B.Praktikum', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1004', 'nama_akun' => 'Peninjauan Kurikulum', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1005', 'nama_akun' => 'Seminar Ilmiah Mahasiswa', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1006', 'nama_akun' => 'Upgrade Internal Dosen', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1007', 'nama_akun' => 'Biaya UTS/UAS', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1008', 'nama_akun' => 'Kepanitiaan Skripsi/TA/Tugas Proyek', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1009', 'nama_akun' => 'Kepanitiaan KKN/PKL', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1010', 'nama_akun' => 'Pendalaman Bahasa Inggris', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1011', 'nama_akun' => 'Maintenance Mahasiswa', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1013', 'nama_akun' => 'Sarana Perkuliahan (LCD Proyektor)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1014', 'nama_akun' => 'Sarana Perkuliahan (Lumen 2800)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1015', 'nama_akun' => 'Sarana Perkuliahan (Lumen 300)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1016', 'nama_akun' => 'Sarana Perkuliahan (spidol/whiteboard/pe', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1017', 'nama_akun' => 'Sound system kelas & Lab dan Aula', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1018', 'nama_akun' => 'Biaya Pemeliharaan Lab.Komputer', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1019', 'nama_akun' => 'Pengadaan Buku Perpustakaan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1020', 'nama_akun' => 'Microsoft Campus Agreement', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1021', 'nama_akun' => 'Pembinaan Prakerin', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1022', 'nama_akun' => 'Uang Saku Prakerin', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2000', 'nama_akun' => 'B.Gaji Pejabat&Karyawan(Dosen tetap)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2001', 'nama_akun' => 'B.Gaji Pejabat&Karyawan(Karyawan tetap)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2002', 'nama_akun' => 'B.Gaji Pejabat&Karyawan(HR Mengajar Dose', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2003', 'nama_akun' => 'B.Gaji Pejabat&Karyawan(Asisten Dosen te', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2004', 'nama_akun' => 'B.Gaji Pejabat&Karyawan(Asisten Lab)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2005', 'nama_akun' => 'Rapat Kerja Bidang II', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2006', 'nama_akun' => 'Listrik & Telfon', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2007', 'nama_akun' => 'Pengadaan ATK', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2008', 'nama_akun' => 'Keperluan Rumah Tangga', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2009', 'nama_akun' => 'Biaya Pemeliharaan Sarpras,R.Kuliah,R.La', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2010', 'nama_akun' => 'Pengadaan Inventaris Kantor', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2011', 'nama_akun' => 'Pengadaan Seragam', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2013', 'nama_akun' => 'Kepanitian (Registrasi Semester Ganjil)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2014', 'nama_akun' => 'Kepanitian (Registrasi Semester Genap)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2015', 'nama_akun' => 'Kepanitian (Program Hibah Dikti)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2016', 'nama_akun' => 'Kepanitian (Pengadaan&Renovasi Semester ', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2017', 'nama_akun' => 'Kepanitiaan (Pengadaan&Renovasi semeter ', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2019', 'nama_akun' => 'BPJS & Premi Asuransi (Dosen-Karyawan)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2020', 'nama_akun' => 'Dosen Tetap', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2021', 'nama_akun' => 'Karyawan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2022', 'nama_akun' => 'Sumbangan Sosial(Pernikahan,Kelahiran,Ke', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2024', 'nama_akun' => 'Bantuan Alat Komunikasi (Ketua)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2025', 'nama_akun' => 'Bantuan Alat Komunikasi (Waket&Perintis)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2026', 'nama_akun' => 'Bantuan Alat Komunikasi (Kabag)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2027', 'nama_akun' => 'Bantuan Alat Komunikasi (Kabit)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-2028', 'nama_akun' => 'Pinjaman Karyawan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3000', 'nama_akun' => 'Rapat Kerja Bidang III', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3002', 'nama_akun' => 'Penelitian (Penerbitan Jurnal)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3003', 'nama_akun' => 'Penelitian', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3004', 'nama_akun' => 'Penelitian (Seminar Penelitian Nasional)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3006', 'nama_akun' => 'Pengabdian Masyarakat(Biaya Pengabdian)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3008', 'nama_akun' => 'Kerjasama Antar Lembaga(APTIKOM)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3009', 'nama_akun' => 'Pemberdayaan Alumni', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3010', 'nama_akun' => 'Bursa Kerja', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3011', 'nama_akun' => 'Temu Almuni', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3012', 'nama_akun' => 'Program Kreatifitas Mahasiswa', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3013', 'nama_akun' => 'Penerimaan STIKOM Bebagi/Peduli', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3014', 'nama_akun' => 'PLK', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3015', 'nama_akun' => 'Kewirausahaan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3016', 'nama_akun' => 'Asuransi Mahasiswa', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3017', 'nama_akun' => 'UKM', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3019', 'nama_akun' => 'Pengembangan Minat Bakat Mahasiswa', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3020', 'nama_akun' => 'Keikutsertaan Dalam Kegiatan Pemda', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3021', 'nama_akun' => 'Karnaval/Geral Jalan/Upacara', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3023', 'nama_akun' => 'Kepanitiaan (Wisuda)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3024', 'nama_akun' => 'Kepanitiaan (PLK)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3025', 'nama_akun' => 'Kepanitiaan (PMB)', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3026', 'nama_akun' => 'Kepanitiaan (Program Penelitian & Pengem', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-3027', 'nama_akun' => 'Kepanitiaan (Program Pengabdian Masyarak', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0085', 'nama_akun' => 'Arisan', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0086', 'nama_akun' => 'Lain-lain', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0087', 'nama_akun' => 'Honor/Tunjangan non Rutin/Gaji 13/THR', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0088', 'nama_akun' => 'insentif lembur & Konusmi Lembur', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0089', 'nama_akun' => 'Buka Bersama & Halal Bihalal', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0090', 'nama_akun' => 'Pajak Bumi Bangunan & Pajak Mobil', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-0091', 'nama_akun' => 'Pinjaman Koperasi', 'created_at' => $now, 'updated_at' => $now),
            array('kode_akun' => '2-1023', 'nama_akun' => 'Konversi Maba Transfer', 'created_at' => $now, 'updated_at' => $now)
        );
        $this->db->table('tbl_akun_pengeluaran')->insertBatch($data);
    }
}
